### ISSUE TITLE
为什么很多项目都是maven呢

### ISSUE THREAD

**Issue by winlans** [open-halo/halo-starter#1]
gradle灵活且简洁，但是为什么大家都是用maven呢，这真的让我好奇。😂

**Comment by thegenius** [comment]
如果是个人项目，比较推荐gradle，因为你能控制住所有的东西。
如果是大型协作型项目，比较推荐maven，因为maven简单，且不容易犯错。
或者说：gradle，下限低，上限高。
maven，下限高，上限低。

**Comment by winlans** [comment]
感谢回复，我们公司一直都是gradle， 所以看到maven感觉真的是太罗嗦了😃，之前用若依，也是改成了gradle。
